### ISSUE TITLE
Protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by AnaCarolcs** [fga-eps-mds/2020.2-Violeta-Documentacao#19]
Um protótipo de baixa fidelidade simula algumas características do projeto, sendo que a ênfase é na funcionalidade e não na estética. Nesse tipo de modelo, geralmente, pretende-se obter um feedback de usuários que farão o teste preliminar.

Características dos protótipos de baixa fidelidade:

- Possui baixo grau de detalhamento;
- Apresenta visualmente a funcionalidade;
- Não possui recursos de interação;
- Não exibe necessariamente o mesmo design da versão final;
- Podem ser realizados no papel.

**Comment by FabianaRibas** [comment]
Foi realizado em 04/03/2021, com o time de MDS, uma reunião de BrainStorm para fazer o protótipo de baixa fidelidade. Segue abaixo o artefato gerado.
![violeta](https://user-images.githubusercontent.com/38467658/110165280-7a64df00-7dd1-11eb-8440-43dd515251f4.png)
