### ISSUE TITLE
Documento de arquitetura

### ISSUE THREAD

**Issue by AnaCarolcs** [fga-eps-mds/2020.2-Violeta-Documentacao#26]
Criar documento de arquitetura do projeto.

**Comment by victorhdcoelho** [comment]
Foi adicionado a visão geral da arquitetura e o documento de template que será utilizado !

**Comment by victorhdcoelho** [comment]
Para realizar a tarefa visualizar o exemplo em https://fga-eps-mds.github.io/2020.1-Grupo6/org_artifacts/architecture_doc/
